export const PRODUCT_PROGRESS = 'PRODUCT_PROGRESS';
export const PRODUCT_FETCH_PROGRESS = 'PRODUCT_FETCH_PROGRESS';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCT_DELETE_PROGRESS = 'PRODUCT_DELETE_PROGRESS';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_UPDATED = 'PRODUCT_UPTATED';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const EVENT_CREATE_PROGRESS = 'EVENT_CREATE_PROGRESS';
export const EVENT_UPDATE_PROGRESS = 'EVENT_UPDATE_PROGRESS';
export const EVENT_DELETE_PROGRESS = 'EVENT_DELETE_PROGRESS';
export const EVENT_FETCH_PROGRESS = 'EVENT_FETCH_PROGRESS';
export const EVENT_CREATED = 'EVENT_CREATED';
export const EVENT_DELETED = 'EVENT_DELETED';
export const EVENTS_FETCHED = 'EVENTS_FETCHED';
export const EVENT_UPDATED = 'EVENT_UPDATED';
export const EVENT_ERROR = 'EVENT_ERROR';

export const CATEGORY_PROGRESS = 'CATEGORY_PROGRESS';
export const CATEGORY_CREATED = 'CATEGORY_CREATED';
export const CATEGORY_DELETED = 'CATEGORY_DELETED';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const AUTH_PROGRESS = 'AUTH_PROGRESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';