export const PRODUCT_PROGRESS = 'PRODUCT_PROGRESS';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_UPTATED = 'PRODUCT_UPTATED';
export const PRODUCTS_SELECTED = 'PRODUCTS_SELECTED';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const PRODUCT_SELECTED = 'PRODUCT_SELECTED';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const CREATE_EVENT = 'CREATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const SELECT_EVENTS = 'SELECT_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const EVENT_ERROR = 'EVENT_ERROR';


export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const SELECT_CATEGORIES = 'SELECT_CATEGORIES';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

export const AUTH_PROGRESS = 'AUTH_PROGRESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';